datasource:
  stone:
    connection-timeout: 50000
    driver-class-name: oracle.jdbc.OracleDriver
    initial-size: 2
    max-active: 5
    max-idle: 1
    max-wait: 10000
    maximum-pool-size: 1
    min-idle: 1
    password: pob6y1o6st6j78k5
    test-on-borrow: true
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
    type: com.alibaba.druid.pool.DruidDataSource
    jdbc-url: jdbc:oracle:thin:@//10.200.2.54:1521/stonetemp
    username: wu_wdp
    validation-query: select 1 from dual
